### PR TITLE
REQ-403: set up branch 

### PR DESCRIPTION
**Pull request by psafont**
Both xen-api and xen-api-libs-transitional have changes, track them with this branch.

### CODE REVIEW

**Review by lippirk — APPROVED** [review]
The urls are confusing, because the branch is called `feature/REQ-403` and not `feature/REQ-403/master`, however they do appear to fetch the correct tarballs

**Comment by psafont** [comment]
This PR is wrong, it should not be merged to master.

**Comment by lindig** [comment]
This looks good but do the corresponding branches in the other repos exist already?

**Review by lindig — APPROVED** [review]

**Comment by psafont** [comment]
Branches in xen-api and xen-api-libs-transitional have been set up.

**Pull request merged**
