### PR TITLE
CP-34942: Update dune to 2.9.1 and ocamlfindlib to 1.9.1

### PR DESCRIPTION
**Pull request by psafont**
Ocamlfind:
```
-  1.9.1: Fixes a few install-related issues, like missing files.
   
-  1.9: Overhaul how separately installed packages (e.g. num)  are handled (by 
   David Allsopp).
   Switch to opam-2.0 file format (by David Allsopp).
   Fix an incomaptibility with ocaml-4.13 (by David Allsopp).
   Expose the native toplevel (by Louis Gesbert).
   Fix an incompatibility with "Jane Street Style" (by Mark Laws).
   Switch from m4 to sed (by kit-ty-kate).
```

Dune:
```
2.9.1 (07/09/2021)
    Don't use subst --root in Opam files (#4806, @MisterDA)
    Fix compilation on Haiku (#4885, @Sylvain78)
    Allow depending on ocamldoc library when ocamlfind is not installed. (#4811, fixes #4809, @nojb)
    Fix (enabled_if ...) for installed libraries (#4824, fixes #4821, @dra27)
    Create more future-proof opam files using --promote-install-files=false (#4860, @bobot)

2.9.0 (29/06/2021)
    Add (enabled_if ...) to (mdx ...) (#4434, @emillon)
    Add support for instrumentation dependencies (#4210, fixes #3983, @nojb)
    Add the possibility to use locks with the cram tests stanza (#4397, @voodoos)
    Allow to set up merlin in a variant of the default context (#4145, @TheLortex, @voodoos)
    Add (package ...) to (mdx ...) (#4691, fixes #3756, @emillon)
    Handle renaming of coq.kernel library to coq-core.kernel in Coq 8.14 (#4713, @proux01)
    Fix generation of merlin configuration when using (include_subdirs unqualified) on Windows (#4745, @nojb)
    Fix bug for the install of Coq native files when using (include_subdirs qualified) (#4753, @ejgallego)
    Allow users to specify install target directories for doc and etc sections. We add new options --docdir and --etcdir to both Dune's configure and dune install command. (#4744, fixes #4723, @ejgallego, thanks to @JasonGross for reporting this issue)
    Fix issue where Dune would ignore (env ... (coq (flags ...))) declarations appearing in dune files (#4749, fixes #4566, @ejgallego @rgrinberg)
    Disable some warnings on Coq 8.14 and (lang coq (>= 0.3)) due to the rework of the Coq "native" compilation system (#4760, @ejgallego)
    Fix a bug where instrumentation flags would be added even if the instrumentatation was disabled (@nojb, #4770)
    Fix #4682: option -p takes now precedence on environement variable DUNE_PROFILE (#4730, #4774, @bobot, reported by @dra27 #4632)
    Fix installation with opam of package with dune sites. The .install file is now produced by a local dune install during the build phase (#4730, #4645, @bobot, reported by @kit-ty-kate #4198)
    Fix multiple issues in the sites feature (#4730, #4645 @bobot, reported by @Lelio-Brun #4219, by @Kakadu #4325, by @toots #4415)
```

### CODE REVIEW

**Comment by psafont** [comment]
Waiting on dune 2.9.1 t be merged on the official repo, 2.9.1 got released yesterday: https://github.com/ocaml/opam-repository/pull/19420

**Comment by psafont** [comment]
It found an unused package :)
```
Run tools/find-unused-packages.sh
--- .github/unused-upstream.txt	2021-09-08 09:07:12.463378146 +0000
+++ /dev/fd/63	2021-09-08 09:16:36.803681801 +0000
@@ -1,4 +1,5 @@
 bisect_ppx
+conf-m4
 conf-perl
 fix
 logs-syslog
```

**Review by lindig — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
> Waiting on dune 2.9.1 to be merged on the official repo, 2.9.1 got released yesterday: [ocaml/opam-repository#19420](https://github.com/ocaml/opam-repository/pull/19420)

Merged

**Comment by psafont** [comment]
Thanks!

**Review by edwintorok — APPROVED** [review]

**Comment by lindig** [comment]
We can merge this - it will be only used in the CI because we will have to make a release to use it on other builds.

**Pull request merged**
