### PR TITLE
Update qmp to 0.13.0

### PR DESCRIPTION
**Pull request by lindig**
a2bf522 CP-27111: add Qmp.Device.VCPU.id_of to the public interface
fa45218 CP-27111: implement QMP query-hotpluggable-cpus command
03fab5f CP-27111: implement QMP device_add command for VCPUs
660ec57 CP-27111: implement QMP device_add command according to specifi..

Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
The failure is surprising. is xenopsd currently broken?
```
#=== ERROR while installing xapi-xenopsd-xc.master ============================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p xapi-xenopsd-xc -j 4
# path                 /home/opam/.opam/4.04.2/build/xapi-xenopsd-xc.master
# compiler             4.04.2
# exit-code            1
# env-file             /home/opam/.opam/4.04.2/build/xapi-xenopsd-xc.master/xapi-xenopsd-xc-591-905464.env
# stdout-file          /home/opam/.opam/4.04.2/build/xapi-xenopsd-xc.master/xapi-xenopsd-xc-591-905464.out
# stderr-file          /home/opam/.opam/4.04.2/build/xapi-xenopsd-xc.master/xapi-xenopsd-xc-591-905464.err
### stderr ###
# [...]
# File "xc/device.ml", line 1417, characters 48-73:
# Error: This expression has type 'a * 'b * 'c
#        but an expression was expected of type Qmp.device_add_t
#       ocamlc xc/.xenops_xc_main.eobjs/xenops_server_xen.{cmi,cmo,cmt}
# File "xc/xenops_server_xen.ml", line 681, characters 16-30:
# Warning 3: deprecated: Xenops_utils.String.set
# Use Bytes.set instead.
# File "xc/xenops_server_xen.ml", line 874, characters 28-47:
# Warning 3: deprecated: Xenops_utils.String.set
# Use Bytes.set instead.
```

**Comment by lindig** [comment]
I have to check against the `qemu-upstream` branch of xenopsd where this should work.

**Comment by lindig** [comment]
Closing this for now - this requires updates in xs-opam that are not yet on the master branch.

**Comment by lindig** [comment]
We are about to merge the QEMU branch which includes the required changes in xenopsd. The test on Travis will fail because it does not yet have the changes.

**Pull request merged**
