### PR TITLE
Add Angstrom 0.6.0

### PR DESCRIPTION
**Pull request by jonludlam**
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

### CODE REVIEW

**Comment by lindig** [comment]
```

**Comment by lindig** [comment]
```
[ERROR] angstrom.0.6.0 is not available because your system doesn't comply with
        ocaml-version >= "4.03.0".
```

**Comment by mseri** [comment]
Time to move to OCaml 4.04? ...

**Comment by thomassa** [comment]
Closing this for the time being, since apparently it's blocked on an OCaml upgrade (or needs work to make it compatible with an earlier OCaml version).

**Pull request closed without merging**
