### PR TITLE
Add constaint to message-switch

### PR DESCRIPTION
**Pull request by jonludlam**
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
I think this is already contained in https://github.com/xapi-project/xs-opam/pull/47
do we need =?

**Comment by jonludlam** [comment]
well we probably need a minimum at least. I just got a build error when trying to build against 2.1.0: https://travis-ci.org/jonludlam/xcp-idl#L829

**Comment by mseri** [comment]
I am happy to add `=`, please fix the merge conflict. However the travis build is wrong in general because it tries to use the global opam on top of xs-opam instead of using only xs-opam (using EXTRA_REPO in place of BASE_REPO in the travis file)

**Comment by jonludlam** [comment]
true, but I plan to put some of these opam packages into the main opam-repository, in which case we'll need these sorts of constraints.

**Comment by jonludlam** [comment]
Gabor's fix should work for me

**Pull request closed without merging**
