### PR TITLE
CP-17621: Add infrastructure for QMP (QEMU Monitor Protocol) to xenopsd

### PR DESCRIPTION
**Pull request by fillzero**
Signed-off-by: Liang Dai <liang.dai1@citrix.com>

### CODE REVIEW

**Comment by fillzero** [comment]
@lindig @jonludlam 
Would you please help merge and make new release.

Note:
It looks like this PR (https://github.com/ocaml/opam-repository/pull/9127) causes travis CI build failed.

**Comment by lindig** [comment]
The INRIA website had problems yesterday and caused Travis builds to fail. I'll give it another try. I'll merge the PR later.

**Comment by lindig** [comment]
Travis reports - please fix:

```
Errors found in ~/build/xapi-project/xs-opam/packages/xs/qmp.0.9.1/opam:
    error 25: Missing field 'authors'
    error 35: Missing field 'homepage'
  warning 36: Missing field 'bug-reports'
```

**Comment by fillzero** [comment]
@lindig - Added, thanks
```
authors: [ "Dave Scott" ]
homepage: "https://github.com/xapi-project/ocaml-qmp"
bug-reports: "https://github.com/xapi-project/ocaml-qmp/issues"
```

**Pull request merged**
