### PR TITLE
Check missing test-only dependencies and add missing ppx_driver and conf-ncurses

### PR DESCRIPTION
**Pull request by edwintorok**
Travis on xcp-idl now failed with missing `ppx_driver` dependency.
Add a test in xs-opam that checks for missing test-only dependencies, so
we can find them all more easily.

This command can be used locally to quickly check this (it won't actually build the packages just check that they are installable)
```
BASE_REMOTE=/xs-opam CHECK_DEPENDENCIES=1 COMPILE_ALL=1 OCAML_VERSION=4.06.0 DISTRO=centos-7 tools/build-docker.sh
```

### CODE REVIEW

**Comment by mseri** [comment]
I think `check_unused` and `check_dependencies` should be two separate tests. The first is to make sure that the packages in `xs` are only the ones really needed by xapi, the other is to make sure that we can run the tests in travis

**Comment by edwintorok** [comment]
We've run them as one step to conserve Travis resources, most of the overhead is in starting a new build step, once running we can easily test for both. I agree that it makes it harder to see or fix just one of the problems, and the precedence is not correct: we care more about tests running than having unused packages.

**Comment by edwintorok** [comment]
Maybe we could use build stages: put the one checking for (test) dependencies as first stage, and skipping all other builds if that one fails, and have the other ones all part of second stage: https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions

**Comment by mseri** [comment]
Yes and no. Bloating the installed xs-opam in Jenkins will slow down the build

**Comment by mseri** [comment]
I like your suggestion

**Comment by edwintorok** [comment]
Still testing it, looks like it only picked up one build stage.

**Comment by edwintorok** [comment]
Looks like it correctly picked up both stages now, had to separate the two `env` lines

**Pull request merged**
