### PR TITLE
[WIP] xs-opam: auto update

### PR DESCRIPTION
**Pull request by mseri**
Updated:

- cohttp: 1.0.2 -> 1.1.0
- cohttp-*: fixed version, was v1.0.2, is now 1.0.2
- ~~lwt: 3.3.0 -> 4.0.0~~
- ~~lwt_log: 1.0.0 -> 1.1.0~~
- jbuilder: 1.0+beta19.1 -> 1.0+beta20

Manually patched (to follow new lwt package/library names):

- shared-block-ring: 2.4.0 -> 2.4.0+1
- vhd-format-lwt: 0.9.2 -> 0.9.2+1

(both patches are innocuous and already submitted upstream)

Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
The temporary commit can be removed after https://github.com/xapi-project/nbd/pull/124 is merged

**Comment by mseri** [comment]
Don't merge for now. There is a missing fix in `cohttp-lwt-unix` that has not yet been released and it's worth waiting for it as it contains a lot of patches

**Comment by lindig** [comment]
What is the current status?

**Comment by mseri** [comment]
I am checking if we can merge the current version without lwt

**Pull request closed without merging**
