### PR TITLE
Move fast-moving packages & dependents to xs-extra

### PR DESCRIPTION
**Pull request by gaborigloi**
Move message-switch, xapi-idl and xapi-forkexecd and all the packages
depending on them to packages/xs-extra.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
Can you mention the ticket name in the commit and PR title?

**Comment by lindig** [comment]
Should we update the `.travis.yml`? It does not build the packages in `xs-extra`.

**Comment by mseri** [comment]
Yes, I think we should install&remove also the packages in xs-extra

**Comment by gaborigloi** [comment]
These packages are already listed in the `XS` variable, we just need to update the comment.

**Pull request merged**
