### PR TITLE
CP-17621: update QMP

### PR DESCRIPTION
**Pull request by fillzero**
Signed-off-by: Liang Dai <liang.dai1@citrix.com>

### CODE REVIEW

**Comment by fillzero** [comment]
@lindig @jonludlam 
I would like to upgrade this module to version 0.9.4 which supports more QMP commands such as:
https://github.com/xapi-project/ocaml-qmp/blob/master/lib/qmp.mli#L52

**Comment by mseri** [comment]
The install step (the uninstall as well) in opam seems broken, it is trying to install the package in the wrong folder. Please fix that for this to be merged.

**Comment by fillzero** [comment]
@mseri  - The travis log shows 
```
#=== ERROR while installing ezxenstore.0.1.1 ==================================#
```
I think it's not my bad, would you please help to check.
Thanks.

**Comment by mseri** [comment]
Indeed, it was a spurious failure. Sorry

**Pull request merged**
