### PR TITLE
xapi-networkd: update opam file after port to jbuilder

### PR DESCRIPTION
**Pull request by mseri**
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

### CODE REVIEW

**Comment by lindig** [comment]
is the Travis failure expected and unrelated?

**Comment by gaborigloi** [comment]
Maybe not:
```
#=== ERROR while installing xapi-networkd.master ==============================#

# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)

# os                   linux

# command              jbuilder build -p xapi-networkd -j 4

# path                 /home/opam/.opam/4.04.2/build/xapi-networkd.master

# compiler             4.04.2

# exit-code            1

# env-file             /home/opam/.opam/4.04.2/build/xapi-networkd.master/xapi-networkd-481-d8a6f3.env

# stdout-file          /home/opam/.opam/4.04.2/build/xapi-networkd.master/xapi-networkd-481-d8a6f3.out

# stderr-file          /home/opam/.opam/4.04.2/build/xapi-networkd.master/xapi-networkd-481-d8a6f3.err

### stderr ###

# Error: I don't know about package xapi-networkd (passed through --only-packages/--release)

# Hint: did you mean xcp-networkd?

```

**Comment by mseri** [comment]
We need to rename the library and opamfile in xcp-networkd.git to xapi-networkd.opam. I missed it when reviewing

**Comment by mseri** [comment]
Renamed with https://github.com/xapi-project/xcp-networkd/pull/119 (re-running tests)

**Pull request merged**
