### PR TITLE
CP-34942: minor updates for upstream libraries

### PR DESCRIPTION
**Pull request by psafont**
These are all minor updates with fixes.

I've left out some updates that need changes:
- the crypto libraries: elliptical crypto must be taken into account by users
- ssl: broken for the version of openssl used in dom0: https://github.com/savonet/ocaml-ssl/issues/70
- cohttp + conduit: system-certs are used by default instead of none. Need to check how to generate an authenticator and inject it there.
- ctypes: errno-unix must be updated to use -thread when compiling (or port it to dune), https://github.com/xapi-project/ocaml-pci/pull/4
- mirage: need adapt vhd-tool to the mirage versions that use lwt implicitely.

### CODE REVIEW

**Review by lindig — APPROVED** [review]

**Review by lippirk — APPROVED** [review]

**Comment by lindig** [comment]
Is it worth fixing

```
version       1.1.0
repository    xs-opam
url.src:      "https://bitbucket.org/zandoye/charinfo_width/get/1.1.0.tar.gz"
url.checksum: "md5=c4ab038e06f06a29692c05fdd7c268c5"
homepage:     "https://bitbucket.org/zandoye/charinfo_width/"
bug-reports:  "https://bitbucket.org/zandoye/charinfo_width/issues"
dev-repo:     "hg+https://bitbucket.org/zandoye/charinfo_width"
authors:      "ZAN DoYe"
maintainer:   "zandoye@gmail.com"
license:      "MIT"
depends:      "ocaml" {>= "4.02.3"}
              "result"
              "camomile" {>= "1.0.0" & < "2.0~"}
              "dune"
              "ppx_expect" {with-test & < "v0.13"}
synopsis      Determine column width for a character
description   This module is implemented purely in OCaml and the width function follows the prototype of POSIX's wcwidth.
```

The `url.src` does not work. I believe it was changed:

```
url.src:      "https://github.com/kandu/charInfo_width/archive/1.1.0.tar.gz"
url.checksum: "md5=a539436d1da4aeb93711303f107bec7e"
```

**Comment by lindig** [comment]
The following also does not seem to exist:

```
fileutils.0.5.3/opam:    "https://forge-static.ocamlcore.org/frs/download.php/1728/ocaml-fileutils-0.5.3.tar.gz"
```

**Comment by psafont** [comment]
One of the dependencies is creating problems for the resources library in libs transitional:

```
Testing `Safe_resources'.
This run has ID `02CD6964-F99C-4594-AD6C-3DB927D77721'.

  [OK]          Safe                      0   File "resources/test/safe_test....
  [OK]          Safe                      1   File "resources/test/safe_test....
  [OK]          Safe                      2   File "resources/test/safe_test....
  [OK]          Safe                      3   File "resources/test/safe_test....
  [OK]          Safe                      4   File "resources/test/safe_test....
  [OK]          Safe                      5   File "resources/test/safe_test....
  [OK]          Safe                      6   File "resources/test/safe_test....
  [OK]          Unixfd finaliser          0   File "resources/test/unixfd_tes...
  [FAIL]        Unixfd finaliser          1   File "resources/test/unixfd_tes...
  [FAIL]        Unixfd finaliser          2   File "resources/test/unixfd_tes...

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        Unixfd finaliser          1   File "resources/test/unixfd_...  │
└──────────────────────────────────────────────────────────────────────────────┘
.
..
0
1
2
3
4
5
.
..
0
1
2
3
4
5
6
7
.
..
0
1
2
3
4
5
test.exe: [DEBUG] Memory usage (words): 11350 -> 11344
ASSERT count of open FDs after pipe 2 higher
ASSERT count of open FDs same as original
ASSERT memory leak in words
FAIL memory leak in words

   Expected: `0'
   Received: `-6'
Raised at file "src/alcotest-engine/test.ml", line 174, characters 4-114
Called from file "src/alcotest-engine/core.ml", line 277, characters 17-23
Called from file "src/alcotest-engine/monad.ml", line 34, characters 31-35


Logs saved to `~/code/toolstack/xen-api-libs-transitional/_build/default/resources/test/_build/_tests/Safe_resources/Unixfd finaliser.001.output'.
 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        Unixfd finaliser          2   File "resources/test/unixfd_...  │
└──────────────────────────────────────────────────────────────────────────────┘
.
..
0
1
2
3
4
5
.
..
0
1
2
3
4
5
6
7
[unix_fd]: resource leak detected, allocated at File "resources/test/unixfd_test.ml", line 41, characters 24-31
[unix_fd]: resource leak detected, allocated at File "resources/test/unixfd_test.ml", line 41, characters 24-31
.
..
0
1
2
3
4
5
test.exe: [DEBUG] Memory usage (words): 11483 -> 11477
ASSERT memory leak in words
FAIL memory leak in words

   Expected: `0'
   Received: `-6'
Raised at file "src/alcotest-engine/test.ml", line 174, characters 4-114
Called from file "resources/test/unixfd_test.ml", line 62, characters 12-52
Called from file "src/alcotest-engine/core.ml", line 277, characters 17-23
Called from file "src/alcotest-engine/monad.ml", line 34, characters 31-35


Logs saved to `~/code/toolstack/xen-api-libs-transitional/_build/default/resources/test/_build/_tests/Safe_resources/Unixfd finaliser.002.output'.
 ──────────────────────────────────────────────────────────────────────────────

Full test results in `~/code/toolstack/xen-api-libs-transitional/_build/default/resources/test/_build/_tests/Safe_resources'.
2 failures! in 0.005s. 10 tests run.
```

It's not obvious to me which one of the updated libraries could cause this.

**Comment by lindig** [comment]
The resources module does not use any of the dependencies as far as I can see. So the failure is surprising. Could this be related to the updated compiler? I don't see a failure before this PR, through. But maybe some assumptions in the resources module depend on behavior that could change?

**Comment by psafont** [comment]
Tests are fixed by https://github.com/xapi-project/xen-api-libs-transitional/pull/102

**Pull request merged**
