### PR TITLE
ocaml-rpc: fix version to 1.9.8 but keep opam file

### PR DESCRIPTION
**Pull request by lindig**
This commit does not upgrade to the opam file inside the repository of
ocaml-rpc because I have doubts that it is working. The diff is:

    :xs-opam $ diff -c packages/xs/rpc.1.9.8.jonludlam/opam ~/src/ocaml-rpc/opam
    *** packages/xs/rpc.1.9.8.jonludlam/opam	2017-02-10 12:17:54.160015895 +0000
    --- /home/lindig/src/ocaml-rpc/opam	2017-01-06 15:24:28.553450204 +0000
    ***************
    *** 20,27 ****
        "cow"
        "xmlm"
        "lwt"
    -   "cmdliner"
    -   "rresult"
    -   "async"
      ]
    ! depopts: [ "js_of_ocaml" ]
    \ No newline at end of file
    --- 20,24 ----
        "cow"
        "xmlm"
        "lwt"
      ]
    ! depopts: [ "js_of_ocaml" ]

The package uses cmdliner but does not have it in its opam file that is
part of the source code.

Signed-off-by: Christian <christian.lindig@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
@lindig @jonludlam I have added some modifications to Jon's `ppx2` branch to add some missing dependencies to the `opam` file, I should have sent a PR for that. This is the branch containing the new commits, and its [Travis CI build](https://travis-ci.org/gaborigloi/ocaml-rpc) is passing: <https://github.com/gaborigloi/ocaml-rpc/tree/ppx2>

I think the `opam` file in that branch should be ok now, I removed the `configure` step from the `opam` build steps as there is no configure file, not sure why it worked with that step. The `js_of_ocaml` dependency is also required by the `rpc_client_js` library in the `_oasis` file.

**Comment by lindig** [comment]
I suggest you submit a PR for the source repo and I'll take the opam file from there once it is merged.

**Comment by gaborigloi** [comment]
PR submitted: https://github.com/jonludlam/ocaml-rpc/pull/3

**Comment by gaborigloi** [comment]
@lindig I think some modifications will be required to the `opam` file, for example the one in the source repository has an updated `opam-version`, without which the build seems to fail on Travis. Also, the `uuidm` package is required by the library.

**Comment by gaborigloi** [comment]
Looks good, now I assume we only have to wait until the above PR is merged :smiley: 

When I modified `ounit` to make it a test dependency, the Travis build passed: https://travis-ci.org/gaborigloi/xen-api-client
So it seems we could indeed change `ounit` to `{test}`.

**Comment by lindig** [comment]
I have added the suggested `opam` file for `ocaml-rpc` and will test this. Now all libraries should point to fixed versions.

**Pull request merged**
