### PR TITLE
Use ocaml 4.10 instead of 4.09 in CI builds

### PR DESCRIPTION
**Pull request by stormi**
A first CI test build with ocaml 4.10

Related to https://github.com/xcp-ng/xcp/issues/422

### CODE REVIEW

**Comment by psafont** [comment]
4.10 looks like it needs the rpclibs updated to 7.1.0, this seems to need quite a few updates.

I don't like that it needs conduit updated, even when done, this work will need testing to check it doesn't break anything in xenserver (I'll run tests internally)

```
$ env OPAMNO=true opam upgrade ppx_deriving_rpc=7.1.0 | grep -E "↗|∗"
  ↗ upgrade   jane-street-headers      v0.12.0 to v0.14.0 [required by core_kernel]
  ↗ upgrade   rpclib                   6.1.0 to 7.1.0     [required by ppx_deriving_rpc]
  ↗ upgrade   sexplib0                 v0.12.0 to v0.14.0 [required by base]
  ↗ upgrade   macaddr                  3.1.0 to 5.0.0     [required by ipaddr]
  ↗ upgrade   rpclib-lwt               6.1.0 to 7.1.0     [uses rpclib]
  ↗ upgrade   base                     v0.12.2 to v0.14.0 [required by ppxlib]
  ↗ upgrade   ipaddr                   3.1.0 to 5.0.0     [required by xapi-clusterd-test]
  ↗ upgrade   variantslib              v0.12.0 to v0.14.0 [uses base]
  ↗ upgrade   typerep                  v0.12.0 to v0.14.0 [uses base]
  ↗ upgrade   stdio                    v0.12.0 to v0.14.0 [required by ppxlib]
  ↗ upgrade   parsexp                  v0.12.0 to v0.14.0 [uses base]
  ↗ upgrade   fieldslib                v0.12.0 to v0.14.0 [uses base]
  ↗ upgrade   ppxlib                   0.8.1 to 0.13.0    [required by ppx_deriving_rpc]
  ↗ upgrade   sexplib                  v0.12.0 to v0.14.0 [uses sexplib0]
  ∗ install   ppx_fixed_literal        v0.14.0            [required by ppx_jane]
  ∗ install   ppx_cold                 v0.14.0            [required by ppx_base]
  ↗ upgrade   ppx_variants_conv        v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_typerep_conv         v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_stable               v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_sexp_conv            v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_pipebang             v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_optional             v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_optcomp              v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_let                  v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_js_style             v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_here                 v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_fields_conv          v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_enumerate            v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_deriving_rpc         6.1.0 to 7.1.0
  ↗ upgrade   ppx_compare              v0.12.0 to v0.14.0 [uses ppxlib]
  ∗ install   ipaddr-sexp              5.0.0              [required by conduit]
  ↗ upgrade   ppx_custom_printf        v0.12.1 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_sexp_value           v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_sexp_message         v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_fail                 v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_hash                 v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_assert               v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   conduit                  1.4.0 to 2.1.0     [uses ppx_sexp_conv]
  ↗ upgrade   bin_prot                 v0.12.0 to v0.14.0 [uses base]
  ↗ upgrade   ppx_base                 v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   jst-config               v0.12.0 to v0.14.0 [uses base]
  ↗ upgrade   conduit-lwt              1.4.0 to 2.1.0     [uses ppx_sexp_conv]
  ↗ upgrade   ppx_bin_prot             v0.12.1 to v0.14.0 [uses ppxlib]
  ∗ install   ppx_string               v0.14.0            [required by ppx_jane]
  ↗ upgrade   time_now                 v0.12.0 to v0.14.0 [uses base]
  ↗ upgrade   conduit-lwt-unix         1.4.0 to 2.2.2     [uses ppx_sexp_conv]
  ↗ upgrade   ppx_module_timer         v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_inline_test          v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_expect               v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_bench                v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   splittable_random        v0.12.0 to v0.14.0 [uses base]
  ↗ upgrade   base_quickcheck          v0.12.1 to v0.14.0 [uses ppxlib]
  ↗ upgrade   ppx_jane                 v0.12.0 to v0.14.0 [uses ppxlib]
  ↗ upgrade   base_bigstring           v0.12.0 to v0.14.0 [uses base]
  ↗ upgrade   core_kernel              v0.12.3 to v0.14.0 [uses base]
  ∗ install   timezone                 v0.14.0            [required by core]
  ↗ upgrade   protocol_version_header  v0.12.0 to v0.14.0 [uses core_kernel]
  ↗ upgrade   async_kernel             v0.12.0 to v0.14.0 [uses core_kernel]
  ↗ upgrade   core                     v0.12.4 to v0.14.0 [uses core_kernel]
  ↗ upgrade   async_rpc_kernel         v0.12.0 to v0.14.0 [uses core_kernel]
  ↗ upgrade   async_extra              v0.12.0 to v0.14.0 [uses core_kernel]
  ↗ upgrade   textutils                v0.12.0 to v0.14.0 [uses core_kernel]
  ↗ upgrade   async_unix               v0.12.0 to v0.14.0 [uses core_kernel]
  ↗ upgrade   async                    v0.12.0 to v0.14.0 [uses core_kernel]
  ↗ upgrade   rpclib-async             6.1.0 to 7.1.0     [uses async]
  ↗ upgrade   conduit-async            1.4.0 to 2.1.0     [uses ppx_sexp_conv]
  ↗ upgrade   async_find               v0.12.0 to v0.14.0 [uses ppx_jane]
  ↗ upgrade   async_inotify            v0.12.0 to v0.14.0 [uses ppx_jane]
===== ∗ 5   ↻ 87   ↗ 63 =====
```

**Comment by stormi** [comment]
So, I think all libs are now compatible with both 4.08 and 4.10 in that PR. 

The updated libs caused build failures: cohttp-async and xapi-idl.

ocaml code is out of my area so I'll probably stop here for my part of the work

**Comment by undu** [comment]
`cohttp-async` fails because: `Library "async_extra" not found.` (dune error)
The log doesn't show the error for `xcp-idl`, some tests are runnning.

**Comment by psafont** [comment]
`cohttp-async` fails because it's not compatible with the 0.14.0 async libraries. at least version 2.5.3 is needed.
The log doesn't show the error for `xcp-idl`, some tests are runnning.

**Comment by psafont** [comment]
When applying the changes some breaking changesd around  rpclib appear:
```
[ERROR] The compilation of xapi-xenopsd failed at "/home/paus/.local/share/opam/opam-init/hooks/sandbox.sh build dune build -p xapi-xenopsd -j 11".
File "lib/xenopsd.ml", line 188, characters 8-173:
188 | ........Rpc.
189 |           {
190 |             name= "VM.import_metadata"
191 |           ; params=
192 |               [Rpc.Dict [("debug_info", debug_info); ("metadata", metadata)]]
193 |           }
Error: Some record fields are undefined: notif
```
(some deprecations appear as well)
```
Alert deprecated: Sexplib0.Sexp_conv.sexp_option
[since 2019-03] use [@sexp.option] instead
```

```
[ERROR] The compilation of xapi-datamodel failed at "/home/paus/.local/share/opam/opam-init/hooks/sandbox.sh build dune build -p xapi-datamodel".

File "ocaml/idl/datamodel_values.ml", line 42, characters 16-550:
42 | ................function
43 |     | Rpc.Null -> "Rpc.Null"
44 |     | Rpc.String s -> sprintf "Rpc.String \"%s\"" s
45 |     | Rpc.Int i -> sprintf "Rpc.Int (%LdL)" i
46 |     | Rpc.Int32 i -> sprintf "Rpc.Int32 (%ldl)" i
47 |     | Rpc.Float f -> sprintf "Rpc.Float (%f)" f
48 |     | Rpc.Bool b -> sprintf "Rpc.Bool %b" b
49 |     | Rpc.Dict d -> sprintf "Rpc.Dict [%s]" (String.concat ";" (List.map (fun (n,v) -> sprintf "(\"%s\",%s)" n (aux v)) d))
50 |     | Rpc.Enum l -> sprintf "Rpc.Enum [%s]" (String.concat ";" (List.map aux l))
51 |     | Rpc.DateTime t -> sprintf "Rpc.DateTime %s" t...
Error (warning 8): this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
Base64 _
```

In the tests of xapi-idl this is what fails:
```
File "lib_test/idl_test_common.ml", line 64, characters 30-184:
64 | ..............................struct
65 |   include Xmlrpc
66 | 
67 |   let call_of_string s = call_of_string s
68 | 
69 |   let response_of_string s = response_of_string s
70 | 
71 |   let of_string s = of_string s
72 | end
Error: Signature mismatch:
       ...
       Values do not match:
         val string_of_call : ?strict:bool -> Rpc.call -> string
       is not included in
         val string_of_call : Rpc.call -> string
       File "lib_test/idl_test_common.ml", line 36, characters 2-41:
         Expected declaration
       File "src/lib/xmlrpc.mli", line 8, characters 0-55: Actual declaration
```

**Comment by psafont** [comment]
The last commit links to the patchqueues that make the toolstack compatible with rpclib 7 and Hanestreet's core 0.13.

AFAIK what is missing is updating cohttp and ocamlformat, as mentioned above.

**Comment by edwintorok** [comment]
If we update ocamlformat then it'll fail formatting the repos that have the ocamlformat version embedded in it: we require the ocamlformat version to match exactly. Is the ocamlformat update required?

**Comment by psafont** [comment]
Unfortunately an update Is needed as 14.1 is not compatible with JST 0.14.0, so a change of version is needed, might as well go for the latest version.

On xenopsd a single line is changed by the new version. (In Polly) For xen-api 8 changes are introduced in the whole repository.

I can try in on more repositories if you're interested, as far as I've seen, the biggest disruption is changing the version number in .ocamlformat

**Comment by lindig** [comment]
The number of changes caused by OCamlformat are small enough. I think it's better to pay the price now than later and would vote for updating OCamlformat.

**Review by lindig — APPROVED** [review]

**Review by edwintorok — APPROVED** [review]

**Comment by psafont** [comment]
Merging this to the 4.10 branch, update to 4.10.1 and clean of the xs-extra pins will be done after the branch passes BVTs and BSTs

**Pull request merged**
