### PR TITLE
Add missing package diet: required by Travis on xcp-idl due to mirage-block-unix

### PR DESCRIPTION
**Pull request by edwintorok**
See build failure on https://github.com/xapi-project/xcp-idl/pull/231

### CODE REVIEW

**Comment by gaborigloi** [comment]
Maybe we could put this into `packages/upstream-extra` instead.
Or we could make a new directory for test dependencies, `packages/upstream-testing`

**Comment by lindig** [comment]
If we create a new directory we will have to be careful about our existing scripts that would miss it.

**Comment by mseri** [comment]
If it is used only by tests, it shuold go in `packages/upstream-extra`, otherwise in `packages/upstream`. In any case `packages/diet` is wrong

**Comment by lindig** [comment]
I am not so happy about this PR breaking the existing directory structure and creating a special case. I think `upstream-extra` would work. These packages are available for Travis but are not packaged into the RPMs we are building. Only `upstream` and  `xs` are packaged.

**Comment by edwintorok** [comment]
Good points, I've moved the package.

**Comment by edwintorok** [comment]
Build passed

**Pull request merged**
