### PR TITLE
CP-37282: Update mock xenctrl for TSX changes

### PR DESCRIPTION
**Pull request by edwintorok**
Needs to be done only on Yangtze branch but not on Stockholm branch

### CODE REVIEW

**Comment by psafont** [comment]
The base branch looks good but the url does not exist.

**Comment by edwintorok** [comment]
URL should be fixed now (I had origin pointing to a local file:// URL, so `git push --tags` did nothing useful)

**Comment by edwintorok** [comment]
I think I need to update the workflow, it didn't get triggered, it looks for stockholm

**Comment by edwintorok** [comment]
Build passed

**Review by psafont — APPROVED** [review]

**Review by lippirk — APPROVED** [review]

**Comment by edwintorok** [comment]
Thanks, renamed

**Pull request merged**
