### PR TITLE
Update opam file of xapi-storage-cli

### PR DESCRIPTION
**Pull request by gaborigloi**
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
I'm not sure whether I should add the `base-threads` dependency, as `threads` is a dependency in its `_oasis` file (but I'm not sure why it's required).

**Comment by gaborigloi** [comment]
For some reason the installation of this package is failing.

**Comment by gaborigloi** [comment]
Fixed the issue now, it should install without problems in the Travis build.

**Comment by mseri** [comment]
Given that it's part of the standard distribution, I think it's fine as is.

**Comment by gaborigloi** [comment]
@mseri I looked at the libraries listed as dependencies in its `_oasis` file, and listed them here too as OPAM dependencies.

**Comment by gaborigloi** [comment]
A few of them list `base-threads` as an OPAM dependency.

**Comment by gaborigloi** [comment]
I've added the `base-threads` OPAM dependency.

**Pull request merged**
