### PR TITLE
Print more log lines on build failures

### PR DESCRIPTION
**Pull request by edwintorok**
This should hopefully show us what the build failure is

### CODE REVIEW

**Comment by edwintorok** [comment]
Doesn't seem to work, still prints just very few lines

**Comment by edwintorok** [comment]
PR to fix build here: https://github.com/xapi-project/xen-api/pull/4062

**Comment by lindig** [comment]
Is this too much? But I agree in principle that more lines are useful.

**Comment by edwintorok** [comment]
We might have to reduce the number if we find out its too much and we hit the Travis log file size limit. However 80 chars * 10000 lines is only ~800 KB

**Pull request merged**
