### PR TITLE
xs-opam: auto update

### PR DESCRIPTION
**Pull request by mseri**
Let's wait for Travis before doing anything, this may require some patches or fixups before being mergeable. Now that all the necessary libraries in opam have been upgraded, releasing a restrictive bound on rpc allows us to move to the new series (with plenty of bug fixes and improvements)

lwt and lwt_log are left out until cohttp with the support for them is released

Upgrades:

- async: v0.10.0->v0.11.0
- async_extra: v0.10.0->v0.11.0
- async_kernel: v0.10.0->v0.11.0
- async_rpc_kernel: v0.10.0->v0.11.0
- async_unix: v0.10.0->v0.11.0
- base: v0.10.0->v0.11.0
- bin_prot: v0.10.0->v0.11.0
- configurator: v0.10.0->v0.11.0
- core: v0.10.0->v0.11.1
- core_kernel: v0.10.0->v0.11.0
- fieldslib: v0.10.0->v0.11.0
- jane-street-headers: v0.10.0->v0.11.0
- ocaml-compiler-libs: v0.10.0->v0.11.0
- ppx_assert: v0.10.0->v0.11.0
- ppx_ast: v0.10.0->v0.11.0
- ppx_base: v0.10.0->v0.11.0
- ppx_bench: v0.10.0->v0.11.0
- ppx_bin_prot: v0.10.0->v0.11.0
- ppx_compare: v0.10.0->v0.11.0
- ppx_core: v0.10.0->v0.11.0
- ppx_custom_printf: v0.10.0->v0.11.0
- ppx_driver: v0.10.4->v0.11.0
- ppx_enumerate: v0.10.0->v0.11.0
- ppx_expect: v0.10.1->v0.11.0
- ppx_fail: v0.10.0->v0.11.0
- ppx_fields_conv: v0.10.0->v0.11.0
- ppx_hash: v0.10.0->v0.11.0
- ppx_here: v0.10.0->v0.11.0
- ppx_inline_test: v0.10.1->v0.11.0
- ppx_jane: v0.10.0->v0.11.0
- ppx_js_style: v0.10.0->v0.11.0
- ppx_let: v0.10.0->v0.11.0
- ppx_metaquot: v0.10.0->v0.11.0
- ppx_optcomp: v0.10.0->v0.11.0
- ppx_optional: v0.10.0->v0.11.0
- ppx_pipebang: v0.10.0->v0.11.0
- ppx_sexp_conv: v0.10.0->v0.11.1
- ppx_sexp_message: v0.10.0->v0.11.0
- ppx_sexp_value: v0.10.0->v0.11.0
- ppx_traverse: v0.10.0->v0.11.0
- ppx_traverse_builtins: v0.10.0->v0.11.0
- ppx_type_conv: v0.10.0->v0.11.0
- ppx_typerep_conv: v0.10.0->v0.11.0
- ppx_variants_conv: v0.10.0->v0.11.0
- protocol_version_header: v0.10.0->v0.11.0
- sexplib: v0.10.0->v0.11.0
- spawn: v0.10.1->v0.12.0
- stdio: v0.10.0->v0.11.0
- typerep: v0.10.0->v0.11.0
- variantslib: v0.10.0->v0.11.0

Updates (changed upstream):

- biniou 1.2.0
- conf-openssl 1
- omd 1.3.1
- ppx_tools 5.0
- ssl 0.5.5

New dependencies:

- parsexp v0.11.0
- ppxlib 0.2.0
- sexplib0 v0.11.0
- splittable_random v0.11.0

### CODE REVIEW

**Comment by lindig** [comment]
Let's wait for Travis.

**Comment by mseri** [comment]
Finally!

**Comment by mseri** [comment]
I believe this is ready for review/merge

**Comment by lindig** [comment]
I believe we have to rely on Travis which tells us that all our libraries and components build with the updated libraries.

**Pull request merged**
