### PR TITLE
Synchronised the xapi opam file with the one in the xen-api repo.

### PR DESCRIPTION
**Pull request by kc284**

### CODE REVIEW

**Comment by lindig** [comment]
I am not sure about the depext changes.  However, we should use the same Opam description in the source repo and in the opam repo. And this PR makes them the same.

**Comment by kc284** [comment]
Hmmm, it may be that these deps need to be copied into the source repo. I'm not sure which are the correct ones, and even more so wheb this commit https://github.com/xapi-project/xs-opam/commit/37a18d037e3dafa5c52c5c23cc3163f896677cfe added them while the commit's message talks about removal...

**Comment by kc284** [comment]
I checked with @mseri and it turns out it's the source repo where the deps need to be corrected.

**Comment by mseri** [comment]
I don't understand why travis is failing. I am investigating it on the side. @gaborigloi have you ever seen that kind of failure?

**Comment by gaborigloi** [comment]
No, I haven't 🤔

**Comment by mseri** [comment]
It's failing to install `blktap-devel` :-(

**Pull request merged**
