### PR TITLE
CP-36682: Upgrade ppxlib to 0.10.0

### PR DESCRIPTION
**Pull request by liulinC**
Signed-off-by: Lin Liu <lin.liu@citrix.com>

### CODE REVIEW

**Comment by liulinC** [comment]
I am really confused with xs-opam-src, xs-opam-repo,  
Some experts from tookstack team may need to help on this.

**Comment by lippirk** [comment]
You'll have to fix this CI error by upgrading ppx_deriving_rpc

```
Error:  No solution for xs-toolstack: The following dependencies couldn't be met:
          - xs-toolstack -> message-switch-cli -> ppx_deriving_rpc -> ppxlib < 0.9.0
```

> I am really confused with xs-opam-src, xs-opam-repo,

You can ignore xs-opam-src - just update xs-opam-repo.spec

To fix your

**Comment by lippirk** [comment]
To get your Stockholm backport to compile, the option remains open to replace occurrences of `let* x = y in` with `y >>= fun x ->`. If updating this package starts pulling in many other package updates, you may find that performing this replacement is the path of least resistance

**Comment by psafont** [comment]
rpclib 7.1.0 is compatible with ppxlib 0.9. That needed a new version of message-switch, xapi-idl and the daemons, I recommend to stay away from updating rpclib, it's a pretty invasive change.

**Comment by liulinC** [comment]
> You'll have to fix this CI error by upgrading ppx_deriving_rpc
> 
> ```
> Error:  No solution for xs-toolstack: The following dependencies couldn't be met:
>           - xs-toolstack -> message-switch-cli -> ppx_deriving_rpc -> ppxlib < 0.9.0
> ```
> 
> > I am really confused with xs-opam-src, xs-opam-repo,
> 
> You can ignore xs-opam-src - just update xs-opam-repo.spec

Thanks @lippirk , but I saw some other packages have dependencies like follows, does this means I need to upgrade all of them

```
ackages/upstream/base_quickcheck.v0.12.1/opam                                                                                                      
  21   "ppxlib"            {>= "0.5.0" & < "0.9.0"}                                                                                                 
                                                                                                                                                    
packages/upstream/ppx_assert.v0.12.0/opam                                                                                                           
  19   "ppxlib"        {>= "0.5.0" & < "0.9.0"}                                                                                                     
                                                                                                                                                    
packages/upstream/ppx_base.v0.12.0/opam                                                                                                             
  20   "ppxlib"        {>= "0.5.0" & < "0.9.0"}                                                                                                     
                                                                                                                                                    
packages/upstream/ppx_bench.v0.12.0/opam                                                                                                            
  16   "ppxlib"          {>= "0.5.0" & < "0.9.0"}                                                                                                   
                                                                                                                                                    
packages/upstream/ppx_bin_prot.v0.12.1/opam                                                                                                         
  18   "ppxlib"   {>= "0.7.0" & < "0.9.0"}                                                                                                          
                                                                                                                                                    
packages/upstream/ppx_compare.v0.12.0/opam                                                                                                          
  16   "ppxlib" {>= "0.5.0" & < "0.9.0"}                                                                                                            
                                                                                                                                                    
packages/upstream/ppx_custom_printf.v0.12.1/opam                                                                                                    
  17   "ppxlib"        {>= "0.7.0" & < "0.9.0"}                                                                                                     
                                                                                                                                                    
packages/upstream/ppx_deriving_rpc.6.1.0/opam                                                                                                       
  14   "ppxlib" {< "0.9.0"}                                                                                                                         
                                                                                                                                                    
packages/upstream/ppx_enumerate.v0.12.0/opam                                                                                                        
  16   "ppxlib" {>= "0.5.0" & < "0.9.0"}                                                                                                            
                                                                                                                                                    
packages/upstream/ppx_expect.v0.12.0/opam                                                                                                           
  25   "ppxlib"            {>= "0.5.0" & < "0.9.0"}                                                                                                 
                                                                                                                                                    
packages/upstream/ppx_fail.v0.12.0/opam                                                                                                             
  17   "ppxlib"   {>= "0.5.0" & < "0.9.0"}                                                                                                          
                                                                                                                                                    
packages/upstream/ppx_fields_conv.v0.12.0/opam                                                                                                      
  17   "ppxlib"    {>= "0.5.0" & < "0.9.0"}                                                                                                         
                                                                                                                                                    
packages/upstream/ppx_hash.v0.12.0/opam                                                                                                             
  18   "ppxlib"        {>= "0.5.0" & < "0.9.0"}

packages/upstream/ppx_here.v0.12.0/opam                                                                                                             
  16   "ppxlib" {>= "0.5.0" & < "0.9.0"}                                                                                                            
                                                                                                                                                    
packages/upstream/ppx_inline_test.v0.12.0/opam                                                                                                      
  16   "ppxlib" {>= "0.5.0" & < "0.9.0"}                                                                                                            
                                                                                                                                                    
packages/upstream/ppx_jane.v0.12.0/opam                                                                                                             
  36   "ppxlib"            {>= "0.5.0" & < "0.9.0"}                                                                                                 
                                                                                                                                                    
packages/upstream/ppx_js_style.v0.12.0/opam                                                                                                         
  17   "ppxlib"   {>= "0.5.0" & < "0.9.0"}                                                                                                          
                                                                                                                                                    
packages/upstream/ppx_let.v0.12.0/opam                                                                                                              
  16   "ppxlib" {>= "0.5.0" & < "0.9.0"}                                                                                                            
                                                                                                                                                    
packages/upstream/ppx_module_timer.v0.12.0/opam                                                                                                     
  19   "ppxlib"   {>= "0.5.0" & < "0.9.0"}                                                                                                          
                                                                                                                                                    
packages/upstream/ppx_optcomp.v0.12.0/opam                                                                                                          
  17   "ppxlib" {>= "0.5.0" & < "0.9.0"}                                                                                                            
                                                                                                                                                    
packages/upstream/ppx_optional.v0.12.0/opam                                                                                                         
  16   "ppxlib" {>= "0.5.0" & < "0.9.0"}                                                                                                            
                                                                                                                                                    
packages/upstream/ppx_pipebang.v0.12.0/opam                                                                                                         
  15   "ppxlib" {>= "0.5.0" & < "0.9.0"}                                                                                                            
                                                                                                                                                    
packages/upstream/ppx_sexp_conv.v0.12.0/opam                                                                                                        
  17   "ppxlib"   {>= "0.5.0" & < "0.9.0"}                                                                                                          
                                                                                                                                                    
packages/upstream/ppx_sexp_message.v0.12.0/opam                                                                                                     
  18   "ppxlib"        {>= "0.5.0" & < "0.9.0"}                                                                                                     
                                                                                                                                                    
packages/upstream/ppx_sexp_value.v0.12.0/opam                                                                                                       
  18   "ppxlib"        {>= "0.5.0" & < "0.9.0"}                                                                                                     
                                                                                                                                                    
packages/upstream/ppx_stable.v0.12.0/opam                                                                                                           
  16   "ppxlib" {>= "0.5.0" & < "0.9.0"} 
packages/upstream/ppx_typerep_conv.v0.12.0/opam                                                                                                     
  17   "ppxlib"  {>= "0.5.0" & < "0.9.0"}                                                                                                           
                                                                                                                                                    
packages/upstream/ppx_variants_conv.v0.12.0/opam                                                                                                    
  17   "ppxlib"      {>= "0.5.0" & < "0.9.0"}       
```

**Comment by psafont** [comment]
See https://github.com/xapi-project/xs-opam/pull/511 for the work required to do the update

**Comment by psafont** [comment]
The work to update the package is done in #582

**Pull request closed without merging**
