### PR TITLE
duration: update to 0.1.1 for compatibility with alcotest

### PR DESCRIPTION
**Pull request by mseri**
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
I don't understand how this did not fail when installing `$UPSTREAM` with `xs-opam` as the base repository

**Comment by gaborigloi** [comment]
Probably because we did not ask for the test dependencies, so opam did not consider that version bound.

**Comment by mseri** [comment]
But we ask to install both alcotest and duration, and they have conflicting versions!

**Comment by gaborigloi** [comment]
Only if we want to test duration, because alcotest is a `{test}` dep, so I think if we don't tell that to opam, it will just ignore `{test}` deps completely, including their version bounds. Which kinda makes sense, because we shouldn't be prevented from using a package if it only has conflicts in its test deps and we don't want to test it.

**Comment by mseri** [comment]
Still, we have to make sure that `xs-opam` is fully consistent, tests included, because otherwise it is not reliable for the travis test builds

**Comment by gaborigloi** [comment]
I've added an item to https://github.com/xapi-project/xs-opam/issues/133

**Pull request merged**
