### PR TITLE
Merge master branch into xs-opam next

### PR DESCRIPTION
**Pull request by mseri**
This will require merging `team/ring3/master` into `team/ring3/opam-next` to pick up the new `xen-api-client` spec file

### CODE REVIEW

**Comment by mseri** [comment]
@YarsinCitrix this fixed the build. We need to rebase the branch on the current ring3/master and release a new xs-opam

**Comment by gaborigloi** [comment]
OCaml 4.05 not passing any more :cry:

**Comment by mseri** [comment]
It is failing on `vhd-tool.master`, vhd-tool.masterit may require a patch

**Comment by gaborigloi** [comment]
It used to pass for OCaml 4.05

**Comment by mseri** [comment]
Maybe we have lost the patch in some merge, please have a look

**Comment by gaborigloi** [comment]
Breaking interface change in `ocaml-sha` 1.10, we use 1.9

**Comment by gaborigloi** [comment]
TODO:
* Merge this
* Upgrade to new sha
* Make the 4.05 build compulsory

**Pull request merged**
