### PR TITLE
update feature/REQ-403 to latest master branch

### PR DESCRIPTION
**Pull request by psafont**
This allows the branch to use the latest version of angstrom, which contained breaking changes.

The tests are expected to fail because xen-api has not been adapted to the latest angstrom version.

Since this branch is only used for CI, I recommend merging it and then open a PR for xen-api.

### CODE REVIEW

**Review by lindig — APPROVED** [review]

**Comment by lindig** [comment]
Running the CI after having merged the xapi update (which compiled locally) the CI here fails:

```
#=== ERROR while compiling xapi-libs-transitional.master ======================#
197
# context              2.0.7 | linux/x86_64 | ocaml-system.4.08.1 | file:///home/runner/work/xs-opam/xs-opam
198
# path                 ~/.opam/default/.opam-switch/build/xapi-libs-transitional.master
199
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -j 1
200
# exit-code            1
201
# env-file             ~/.opam/log/xapi-libs-transitional-7396-c03035.env
202
# output-file          ~/.opam/log/xapi-libs-transitional-7396-c03035.out
203
### output ###
204
# This run has ID `BF7A48B8-7BAA-43A8-A6A7-A13EEA71E6E5'.
205
# [...]
206
#   [OK]          Safe                      2   File "resources/test/safe_test.ml", line 88, characters 7-14.
207
#   [OK]          Safe                      3   File "resources/test/safe_test.ml", line 89, characters 7-14.
208
#   [OK]          Safe                      4   File "resources/test/safe_test.ml", line 90, characters 7-14.
209
#   [OK]          Safe                      5   File "resources/test/safe_test.ml", line 91, characters 7-14.
210
#   [OK]          Safe                      6   File "resources/test/safe_test.ml", line 92, characters 7-14.
211
#   [OK]          Unixfd finaliser          0   File "resources/test/unixfd_test.ml", line 87, characters 5-12.
212
#   [OK]          Unixfd finaliser          1   File "resources/test/unixfd_test.ml", line 88, characters 5-12.
213
#   [OK]          Unixfd finaliser          2   File "resources/test/unixfd_test.ml", line 89, characters 5-12.
214
# 
215
# Full test results in `~/.opam/default/.opam-switch/build/xapi-libs-transitional.master/_build/default/resources/test/_build/_tests/Safe_resources'.
216
# Test Successful in 0.000s. 10 tests run.
```

**Comment by psafont** [comment]
I'm unable to reproduce the error in the xapi-libs-transitional, I'll double check whether is the cache that's causing the issue

**Comment by psafont** [comment]
The error is due to a warning as error, see https://github.com/xapi-project/xen-api-libs-transitional/pull/88 for a possible solution.

**Comment by lippirk** [comment]
> The error is due to a warning as error, see [xapi-project/xen-api-libs-transitional#88](https://github.com/xapi-project/xen-api-libs-transitional/pull/88) for a possible solution.
> 
> ```
> # File "http-svr/xmlrpc_client.ml", line 158, characters 63-74:
> # 158 | let with_reusable_stunnel ?use_fork_exec_helper ?write_to_log ?verify_cert host port f =
> #                                                                      ^^^^^^^^^^^
> # Error (warning 27): unused variable verify_cert.
> ```

Let's undraft + merge xapi-project/xen-api-libs-transitional#88?

**Review by lippirk — APPROVED** [review]

**Pull request merged**
